# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/testv2',
                'doc_host': 'https://perceptualrobots.github.io',
                'git_url': 'https://github.com/perceptualrobots/testv2',
                'lib_path': 'testv2'},
  'syms': {'testv2.core': {'testv2.core.foo': ('core.html#foo', 'testv2/core.py')}}}
